import { tools, scripts, notes } from './data';
import './style.css';

const app = document.querySelector<HTMLDivElement>('#app')!;
const categories = ['全部', ...Array.from(new Set(tools.map(t => t.category)))];
let active = '全部';
let mode: 'home' | 'command' | 'weekly' = 'home';

function filteredTools() { return active === '全部' ? tools : tools.filter(t => t.category === active); }
function toolCard(t: typeof tools[number]) { return `<a class="tool-card ${t.private ? 'is-private' : ''}" href="${t.url}" data-category="${t.category}"><span class="tool-icon">${t.icon}</span><span class="tool-name">${t.name}</span><small>${t.desc}</small>${t.badge ? `<em>${t.badge}</em>` : ''}</a>`; }
function renderHome() { return `<section class="hero glass"><div><span class="eyebrow">OneMJJ / Low-maintenance survival center</span><h1>一个 MJJ 的低维护自救中心</h1><p>VPS 检测、三网延迟、自托管入口、PT 媒体、AI API、常用脚本和传家宝笔记，放到一个双端都舒服的工具台。</p><div class="actions"><button data-mode="command">进入控制台</button><button class="ghost" data-mode="weekly">看 MJJ 小报</button></div></div><aside class="status-card"><b>今日状态</b><div><span class="dot ok"></span>Mac mini 在线</div><div><span class="dot ok"></span>Oracle 稳定</div><div><span class="dot warn"></span>三网延迟待接入</div><code>onemjj check gd-cm</code></aside></section><section class="toolbar"><div class="search">⌘K 搜索：YABS、回程、Emby、Sub2API...</div><div class="chips">${categories.map(c=>`<button class="chip ${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('')}</div></section><section class="grid tools-grid">${filteredTools().map(toolCard).join('')}</section><section id="scripts" class="scripts glass"><div><span class="eyebrow">Scripts</span><h2>脚本速查</h2><p>先放常用命令，后面可以加复制、参数生成和真实检测。</p></div><div class="script-list">${scripts.map(s=>`<button class="script" data-copy="${s.cmd.replace(/"/g,'&quot;')}"><b>${s.title}</b><code>${s.cmd}</code></button>`).join('')}</div></section>`; }
function renderCommand() { return `<section class="command-layout"><aside class="nav-panel glass"><b>OneMJJ</b>${['Command','VPS','Network','Selfhosted','Scripts','Notes'].map((n,i)=>`<a class="${i===0?'active':''}">${n}</a>`).join('')}</aside><main class="console glass"><span class="badge">MJJ Command Center</span><h1>买鸡、测鸡、吃灰、复活。</h1><p>这里适合放真实三网 TCPing、回程测试、机器状态和自托管入口。现在是静态原型，结构已经预留。</p><div class="grid mini">${tools.slice(0,8).map(toolCard).join('')}</div><pre>$ onemjj check gd-cm\n广东移动 TCP 443: 28ms\n$ onemjj yabs oracle\nGeekbench / Disk / IPv6 ready</pre></main><aside class="metrics glass"><h3>实时面板</h3>${['广东移动 28ms','广东联通 36ms','广东电信 42ms','Oracle 流量 Safe','最近冲动消费 0 台'].map(x=>`<div><span>${x.replace(/ [^ ]+$/,'')}</span><b>${x.split(' ').at(-1)}</b></div>`).join('')}</aside></section>`; }
function renderWeekly() { return `<section class="weekly"><header><div><h1>OneMJJ Weekly</h1><p>一个 MJJ 的赛博杂物间：工具、脚本、行情和生存手册。</p></div><code>ISSUE 001<br/>onemjj.com</code></header><article class="headline"><span>今日头条</span><h2>这不是导航站，是一份买鸡后的自救报纸。</h2><p>首页保留工具箱效率，同时加入 MJJ 笔记、促销观察、坑点记录和脚本速查。公开看有内容，自己用也方便。</p></article><div class="grid tools-grid paper">${tools.slice(0,8).map(toolCard).join('')}</div><div class="notes">${notes.map(n=>`<article><span>${n.tag}</span><h3>${n.title}</h3><p>${n.body}</p></article>`).join('')}</div></section>`; }
function render() { app.innerHTML = `<nav class="top"><a class="brand" data-mode="home">OneMJJ</a><div><button data-mode="home" class="${mode==='home'?'active':''}">首页</button><button data-mode="command" class="${mode==='command'?'active':''}">控制台</button><button data-mode="weekly" class="${mode==='weekly'?'active':''}">小报</button></div></nav><main>${mode==='home'?renderHome():mode==='command'?renderCommand():renderWeekly()}</main><footer>OneMJJ · 少踩坑，多留传家宝 · Public tools first, private links later.</footer>`; bind(); }
function bind(){ document.querySelectorAll<HTMLElement>('[data-mode]').forEach(el=>el.onclick=()=>{mode=el.dataset.mode as any; active='全部'; render();}); document.querySelectorAll<HTMLButtonElement>('[data-cat]').forEach(el=>el.onclick=()=>{active=el.dataset.cat!; render();}); document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(el=>el.onclick=async()=>{await navigator.clipboard?.writeText(el.dataset.copy||''); el.classList.add('copied'); setTimeout(()=>el.classList.remove('copied'),900);}); }
render();
